[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 8080
  port = 8888
  publish = "."
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
